config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    put :processTask
  end

  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :get_task_id, only: [ :processTask]

  # GET /tasks
  # GET /tasks.json
  def index
    @newTasks = Task.where(:status => "New")
    @inprocessTasks = Task.where(:status => "In Process")
    @blockTasks = Task.where(:status => "Blocked")
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  def processTask

    respond_to do |format|
      if @task_processing.update_attribute(:status, "In Process")
        format.html { redirect_to tasks_path, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_processing }
      else
        format.html { redirect_to tasks_path, notice: 'Task was processed.' }
        format.json { render json: @task_processing.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def get_task_id
      @task_processing = Task.find(params[:task_id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :status, :order, :duedate, :location, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <link href="http://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet">

  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to "Task Manager", root_path %></h1>
      </li>
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">

      <!-- Left Nav Section -->
      <ul class="left">
        <li><%= link_to "New Task", new_task_path %></li>
      </ul>
    </section>
  </nav>
    <%= yield %>

  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :status %>
    <%= f.input :order %>
    <%= f.input :duedate %>
    <%= f.input :location %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<div class="row">
  <div class="small-4 columns">
    <table>
      <thead>
      <tr>
        <th>New Tasks</th>
      </tr>
      </thead>

      <tbody>
      <% @newTasks.each do |task| %>
          <tr>
            <td>
              <div class="callout-card primary radius">
                <div class="card-label">
                </div>
                <div class="callout-card-content">
                  <h4 class="lead"><%= link_to task.name, task %></h4>
                  <div style="float:left;">
                    <%= button_to("Complete", task_processTask_path(task), :method => :put, class: "tiny round button") %>
                  </div>
                </div>
             </div>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="small-4 columns">
    <table>
      <thead>
      <tr>
        <th>In Process Tasks</th>
      </tr>
      </thead>

      <tbody>
      <% @inprocessTasks.each do |task| %>
          <tr>
            <td>
              <div class="callout-card primary radius">
                <div class="card-label">
                </div>
                <div class="callout-card-content">
                  <h4 class="lead"><%= link_to task.name, task %></h4>
                  <div style="float:left;">
                    <a href=<%= edit_task_path(task) %> class="tiny round button">Complete</a>
                    <a href=<%= edit_task_path(task) %> class="tiny round button">Block</a>
                  </div>
                </div>
              </div>
          </div>
          </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="small-4 columns">
    <table>
      <thead>
      <tr>
        <th>Blocked Tasks</th>
      </tr>
      </thead>

      <tbody>
      <% @blockTasks.each do |task| %>
          <tr>
            <td>
            <div class="callout-card primary radius">
              <div class="card-label">
              </div>
              <div class="callout-card-content">
                <h4 class="lead"><%= link_to task.name, task %></h4>
                <div style="float:left;">
                  <a href=<%= edit_task_path(task) %> class="tiny round button">Process</a>
                </div>
              </div>
            </div>
          </div>
          </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Order:</strong>
  <%= @task.order %>
</p>

<p>
  <strong>Duedate:</strong>
  <%= @task.duedate %>
</p>

<p>
  <strong>Location:</strong>
  <%= @task.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>